AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:
    Cakebot code
    
Globals:
    Function:
        Timeout: 20

Parameters:
  PolicyStackNameParameter:
    Type: String
    Default: cakebot-iam
    Description: The name of the stack that declares this stacks IAM policy ARNs

Resources:

    AddBakerFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: AddBakerHandler.handle
            Runtime: nodejs8.10
            Events:
                AddUser:
                  Type: Api
                  Properties:
                    Path: /users/add
                    Method: post

    DeleteBakerFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: DeleteBakerHandler.handle
            Runtime: nodejs8.10
            Events:
                DeleteUser:
                  Type: Api
                  Properties:
                    Path: /users/delete
                    Method: post
    
    GetBakingFunction:
        Type: AWS::Serverless::Function
        Properties:
          CodeUri: src/
          Handler: CalculateBakersHandler.handle
          Runtime: nodejs8.10
          Events:
            Get:
              Type: Api
              Properties:
                Path: /baking
                Method: post
    
    BakersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
        - AttributeName: "UserId"
          AttributeType: "S"
        - AttributeName: "TimesBaked"
          AttributeType: "N"
        - AttributeName: "Baking"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "UserId"
          KeyType: "HASH"
        GlobalSecondaryIndexes:
        - IndexName: BakingThisWeek
          KeySchema:
          - AttributeName: "Baking"
            KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
        - IndexName: OrderedBakers
          KeySchema:
          - AttributeName: "UserId"
            KeyType: "HASH"
          - AttributeName: "TimesBaked"
            KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          
    
# Outputs:

#     CakeBotApi:
#       Description: "API Gateway endpoint URL for Prod stage for cakebot function"
#       Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/CakeBot/"

#     AddBakerFunction:
#       Description: "AddBaker Lambda Function ARN"
#       Value: !GetAtt AddBakerFunction.Arn

#     AddBakerFunction:
#       Description: "AddBaker Lambda Function ARN"
#       Value: !GetAtt AddBakerFunction.Arn

#     AddBakerFunction:
#       Description: "AddBaker Lambda Function ARN"
#       Value: !GetAtt AddBakerFunction.Arn

#     UsersFunctionIamRole:
#       Description: "Implicit IAM Role created for End Retro function"
#       Value: !GetAtt UsersFunctionRole.Arn
